<?php

declare(strict_types=1);

namespace Libxa\Console\Commands\Route;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Libxa\Foundation\Application;
use Libxa\Router\Router;

class CacheCommand extends Command
{
    protected static $defaultName = 'route:cache';

    public function __construct(protected Application $app)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName('route:cache')
             ->setDescription('Create a route cache file for faster route registration');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // Build routes from a *fresh* Router instance loaded straight from
        // routes/web.php + routes/api.php — not the app's Router singleton,
        // which by this point may already be populated from a stale cache
        // file (the console kernel boots the app, including the router
        // service provider, before any command runs).
        $routes = $this->loadFreshRoutes();

        if (empty($routes)) {
            $output->writeln("<comment>No routes registered — nothing to cache.</comment>");
            return Command::SUCCESS;
        }

        $definitions = [];

        foreach ($routes as $route) {
            $action = $route->getAction();

            if ($action instanceof \Closure) {
                $output->writeln(sprintf(
                    "<error>Unable to cache routes:</error> route <comment>%s %s</comment> uses a Closure action, which cannot be cached.",
                    implode('|', $route->getMethods()),
                    $route->getUri()
                ));
                $output->writeln("Convert it to a [Controller::class, 'method'] action, or exclude it from routes/web.php before caching.");
                return Command::FAILURE;
            }

            $definitions[] = [
                'methods'    => $route->getMethods(),
                'uri'        => $route->getUri(),
                'action'     => $action,
                'name'       => $route->getName(),
                'middleware' => $route->getMiddleware(),
            ];
        }

        $cacheFile = $this->app->basePath('src/bootstrap/cache/routes.php');
        $directory = dirname($cacheFile);
        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $export    = var_export($definitions, true);
        $timestamp = date('Y-m-d H:i:s');

        $contents = <<<PHP
<?php

/**
 * Cached routes — generated by `php libxa route:cache` on {$timestamp}.
 * Do not edit this file directly; run `php libxa route:clear` and
 * `php libxa route:cache` again after changing your route files.
 */

return {$export};

PHP;

        file_put_contents($cacheFile, $contents);

        $output->writeln("<info>Routes cached successfully:</info> " . count($definitions) . " route(s) written to {$cacheFile}");

        return Command::SUCCESS;
    }

    /**
     * @return \Libxa\Router\Route[]
     */
    protected function loadFreshRoutes(): array
    {
        $router = new Router($this->app);

        $webRoutes = $this->app->basePath('src/routes/web.php');
        if (file_exists($webRoutes)) {
            $this->requireRouteFile($webRoutes, $router);
        }

        $apiRoutes = $this->app->basePath('src/routes/api.php');
        if (file_exists($apiRoutes)) {
            $this->requireRouteFile($apiRoutes, $router);
        }

        return $router->getRoutes()->all();
    }

    /**
     * Require a route file with $router bound in its local scope, mirroring
     * ServiceProvider::loadRoutesFrom()'s behavior.
     */
    protected function requireRouteFile(string $path, Router $router): void
    {
        require $path;
    }
}
