<?php

declare(strict_types=1);

namespace Libxa\Console\Commands\Config;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Libxa\Foundation\Application;
use Libxa\Config\Config;

class CacheCommand extends Command
{
    protected static $defaultName = 'config:cache';

    public function __construct(protected Application $app)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName('config:cache')
             ->setDescription('Create a cache file for faster configuration loading');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // Build a fresh Config straight from the config/ directory — not the
        // app's bound 'config' singleton, which may already be hydrated
        // from a stale cache file by the time this command runs (the
        // console kernel boots the whole app before any command executes).
        $config = new Config($this->app->configPath());
        $config->load();

        $items = $config->all();

        if (empty($items)) {
            $output->writeln("<comment>No configuration files found — nothing to cache.</comment>");
            return Command::SUCCESS;
        }

        if (! $this->isExportable($items, $badKey)) {
            $output->writeln("<error>Unable to cache configuration:</error> the value at <comment>{$badKey}</comment> is a Closure or object that cannot be safely serialized.");
            $output->writeln("Remove it (or move that logic out of config/) before caching.");
            return Command::FAILURE;
        }

        $cacheFile = $this->app->basePath('src/bootstrap/cache/config.php');
        $directory = dirname($cacheFile);
        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $export    = var_export($items, true);
        $timestamp = date('Y-m-d H:i:s');

        $contents = <<<PHP
<?php

/**
 * Cached configuration — generated by `php libxa config:cache` on {$timestamp}.
 * Do not edit this file directly; run `php libxa config:clear` and
 * `php libxa config:cache` again after changing your config files.
 */

return {$export};

PHP;

        file_put_contents($cacheFile, $contents);

        $output->writeln("<info>Configuration cached successfully:</info> {$cacheFile}");

        return Command::SUCCESS;
    }

    /**
     * Recursively verify every value is safe for var_export() (no Closures,
     * resources, or objects without __set_state support).
     */
    protected function isExportable(mixed $value, ?string &$badKey = null, string $path = ''): bool
    {
        if ($value instanceof \Closure) {
            $badKey = $path ?: '(root)';
            return false;
        }

        if (is_object($value) && ! method_exists($value, '__set_state')) {
            $badKey = $path ?: '(root)';
            return false;
        }

        if (is_array($value)) {
            foreach ($value as $key => $item) {
                if (! $this->isExportable($item, $badKey, $path === '' ? (string) $key : "{$path}.{$key}")) {
                    return false;
                }
            }
        }

        return true;
    }
}
